name: Run Tests CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      garage:
        image: dxflrs/garage:v2.3.0
        ports:
          - 3900:3900
        env:
          GARAGE_DEFAULT_ACCESS_KEY: ${{ secrets.GARAGE_ACCESS_KEY }}"
          GARAGE_DEFAULT_SECRET_KEY: ${{ secrets.GARAGE_SECRET_KEY }}"
          GARAGE_DEFAULT_BUCKET: "default-bucket"


    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.0"

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install dependencies
        run: make

      - name: Create config file
        run: |
          sudo mkdir -p /etc/serverledge
          echo "garage.accessKey=${{ secrets.GARAGE_ACCESS_KEY }}" | sudo tee /etc/serverledge/serverledge-conf.yaml > /dev/null
          echo "garage.secretKey=${{ secrets.GARAGE_SECRET_KEY }}" | sudo tee -a /etc/serverledge/serverledge-conf.yaml > /dev/null

      - name: Run tests
        run: make unit-test && make test
